#Demo Azure pipeline

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'pipeline'
    displayName: 'Azurepipeline'
    jobs:
      - job: 'pipelinetest'
        displayName: 'Running azure pipeline'
        steps:
          - script: echo'mypipeline'
